[metadata]
name = "oxifox"
author = "EdenEast"
origin_url = "https://github.com/EdenEast/nightfox.nvim"

[colors]
foreground = "#C9CCCD"
background = "#172030"
cursor_bg = "#C9CCCD"
cursor_border = "#C9CCCD"
cursor_fg = "#172030"
compose_cursor = '#f49810'
selection_bg = "#214760"
selection_fg = "#C9CCCD"
scrollbar_thumb = "#6e6a86"
split = "#191726"
visual_bell = "#C9CCCD"
ansi = ["#393552", "#db6e89", "#bfdeba", "#d0d6b5", "#3068ac", "#94558d", "#0f9795", "#e0def4"]
brights = ["#716994", "#ff4262", "#51966b", "#f9cb8c", "#214760", "#b200b2", "#3592c4", "#e2e0f7"]

[colors.indexed]
16 = "#b87ea2"
17 = "#f49810"

[colors.tab_bar]
background = "#191726"
inactive_tab_edge = "#191726"
inactive_tab_edge_hover = "#23314a"

[colors.tab_bar.active_tab]
bg_color = "#6e6a86"
fg_color = "#172030"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#23314a"
fg_color = "#cdcbe0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#2f4264"
fg_color = "#C9CCCD"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#172030"
fg_color = "#cdcbe0"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#2f4264"
fg_color = "#C9CCCD"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

